Add ability to chain multiple principals providers
signmykeyio/signmykey pull request #86
Opened 2021-03-20 17:24 UTC by tierpod

Hello. This is next PR that:

* adds ability to chain multiple principals providers
* adds new configuration option: principalsProviders. It doesn't break current deployments, but if principalsProviders and principalsType are both configured, first one will be used
* changes signHandler logic a little. If each of the principals providers returns 0 principals, it isn't an error. If all providers return 0 principals, it's still error.

PS. I know, this PR is still a little big, but it's all about one feature, I don't know how to break it in smaller parts.

2021-03-22 14:51 UTC, pablo-ruth requested changes
Hi,
I don't have many comments, I think it's great code :)

2021-03-22 14:51 UTC, pablo-ruth commented on builtin/principals/ldap/Principals.go
> +		return ctx, []string{}, princsPkg.NewNotFoundError("ldap", "No group found for user "+ldapPrinc.User)
We don't need to add ldapPrinc.User to error, the logger already add it as a field.

2021-03-22 14:51 UTC, pablo-ruth commented on builtin/principals/local/Principals.go
> +		return ctx, []string{}, princsPkg.NewNotFoundError("local", "No principals found for "+local.User)
We don't need to add ldapPrinc.User to error, the logger already add it as a field.

2021-03-22 14:51 UTC, pablo-ruth commented on builtin/principals/local/Principals.go
> +		return ctx, principals, princsPkg.NewNotFoundError("local", "No more principals after trim for "+local.User)
We don't need to add ldapPrinc.User to error, the logger already add it as a field.

2021-03-22 15:24 UTC, pablo-ruth approved these changes

2021-03-22 15:24 UTC, tierpod commented
Thanks! I removed username duplication as you asked

2021-03-22 15:25 UTC, merged

2021-03-22 15:25 UTC, pablo-ruth commented
Thanks for your work, it's merged :)

2021-03-22 15:32 UTC, tierpod commented
Glad to help!

2021-03-24 12:06 UTC, pablo-ruth commented
@tierpod are you working on another PR ? If not I'll release a new version soon.

2021-03-24 12:53 UTC, tierpod commented
@pablo-ruth No, I'm not, this PR was last for this feature.

2021-03-26 09:48 UTC, pablo-ruth commented
This PR is released with signmykey v0.6.0, thanks for your contribution!